function gui_GoogleMapAPI

%% main window
hFig = figure('MenuBar',            'none', ...
                    'Toolbar',              'none', ...
                    'HandleVisibility',  'callback', ...
                    'Name',                'RadOnc Google Map API', ...
                    'NumberTitle',      'off', ...
                    'Units',                 'normalized',...
                    'Position',             [0.1 0.2 0.2 0.4],...
                    'Color',                 'black');
                
w_PB = 0.8;
gap_w = (1-w_PB)/2;
nPB = 3;
gap_h = 0.1;
h_PB = (1-gap_h*(nPB+1))/nPB;

for n = 1:nPB
    y(n) = gap_h*(nPB-n+1)+h_PB*(nPB-n);
end
str = {'Load API Key';
    'Load Zip Code';
    'Get Driving Time'};

CLR = 'ccc';

hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 0, 1, 1], ...
                                'Title', '',...
                                'FontSize',                 11,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'none',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'b',...
                                'ShadowColor',            'b');

for iPB = 1:nPB
    PB(iPB) = uicontrol('parent', hPanel,...
                            'Unit', 'Normalized',...
                            'Position', [gap_w, y(iPB), w_PB, h_PB], ...
                            'Style', 'pushbutton',...
                            'String', str{iPB},...
                            'FontSize', 20, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [1 1 1]*0.25,...
                            'ForegroundColor', CLR(n),...
                            'Visible', 'on', ...
                            'Enable', 'on', ...
                            'Tag', num2str(iPB), ...
                            'Callback', @Callback_Pushbutton_);           
end